.PHONY: all clean

all: clean python_script

clean:
	@echo "Cleaning older files if they exist..."
	@rm -rf html
	@rm -f mapa_sorted_linked.html

python_script:
	@echo "Running script..."
	@python3 script.py
